version: 0.2

phases:
  install:
    runtime-versions:
      node: nodejs16
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync dist/my-app s3://soban-github-angualar --delete
